export enum activityLogActionType {
  Open_Account_Screen = 1,
  Open_Audit_Screen = 2,
  Edit_Client_Wiki = 3,
  Audit_Screen_Save = 4,
  Account_Screen_Save = 5,
  Action_Note_Save = 6,
  Form_Linked = 7,
  Task_Completed = 8,
  Employee_Termed = 9,
  Employee_Un_Termed = 10,
  Employee_Demographic_Update = 11,
  Employee_Contact_Update = 12,
  Authorized_Caller_Update = 13,
  Form_linked_to_iVerify = 14,
  Form_Un_linked_from_iVerify = 15,
  Dependent_Demographic_Update = 16,
  Dependent_Relationship_Update = 17,
  Dependent_Added_to_Audit = 18,
  Dependent_Removed_from_Audit = 19,
  Audit_Component_Added_to_Audit = 20,
  Audit_Component_Removed_from_Audit = 21,
  Requirement_Added_to_Audit = 22,
  Requirement_Removed_from_Audit = 23
}
