import { EmpDependent } from './emp-dependent.model';
import { ObjectState } from './object-state';
import { EmployeeTask } from './employee-task';
import { RemovedReason } from './removed-reason';

export interface Employee {
	Id: number;
	ClientId: number;
	Ssn: string;
	FirstName: string;
	MiddleName: string;
	LastName: string;
	Suffix: string;
	DateOfBirth: Date;
	Gender: string;
	Address1: string;
	Address2: string;
	City: string;
	State: string;
	Zipcode: string;
	Country: string;
	HomePhone: string;
	WorkPhone: string;
	CellPhone: string;
	ContactEmail: string;
	PersonalEmail: string;
	ClientEEId: string;
	SubClientId: string;
	IsTermed: boolean;
	IsVip: boolean;
	IsConsentAccepted: boolean;
	IsPaperless: boolean;
	RunLetters: boolean;
	IsLocked: boolean;
	Criteria1: string;
	Criteria2: string;
	Criteria3: string;
	Criteria4: string;
	Criteria5: string;
	Criteria6: string;
	Criteria7: string;
	Criteria8: string;
	Criteria9: string;
	Criteria10: string;
	RemovedReasonId: number;
	ObjectState: ObjectState;
	Dependents: EmpDependent[];
	RemovedReason: RemovedReason;
	EmployeeTasks: EmployeeTask[];
}
